pull_request_rules:
  - name: automerge to main with label automerge and branch protection passing
    conditions:
      - "#approved-reviews-by>1"
      - base=main
      - label=automerge
    actions:
      merge:
        method: squash
        strict: true
        commit_message: title+body
  - name: backport patches to v0.42.x branch
    conditions:
      - base=main
      - label=backport/0.42.x (Stargate)
    actions:
      backport:
        branches:
          - release/v0.42.x
  - name: backport patches to v0.39.x branch
    conditions:
      - base=main
      - label=backport/0.39.x (Launchpad)
    actions:
      backport:
        branches:
          - launchpad/backports
